;configReal()

Deposit=5000
Currency=USD
Leverage=1:2000

Fragmentacion=True

KeepPrivate=1
Spread=0
UseDate=1
ToDate=2026.03.01

StartUp=False

DefaultSymbol=EURUSD

Autonormalizer=True
Company=
LicenseFile=

_12años=4380
_10años=3650
_9años=3285
_8años=2920
_7años=2555
_6años=2190
_5años=1825
_4años=1460
_3años=1095
_2años=730
_1año=365
_6meses=182

Comando_fulltime=True
AutoFilter_Genetico_Post_Forward=True
AutoFilter_MODO_FRAGMENTADO=True
AutoCargador=True


posicion1=single_mode,"TEST_LOGICA_RAPIDA",_1año,_AUTO_NZER_
posicion2=single_debug,"DEBUG_VISUAL_HUMANO",_1año,_6años,_12años,
posicion3=single_mode,"STRESS_RESISTENCIA",_12años
posicion4=genetica70_fw30,"OPTIMIZACION_GENETICA_FW",_6años,preset,_AUTO_NZER_,_Auto_Filter_Gen_For[1/3]_,{}
posicion5=single_mode_fragmentado,"VALIDACION_STRESS_ANUALIZADO",_12años,Fragmentacion,Full_time,_AUTO_NZER_,_AutoCargador_
